[workspace]

members = [
    "common",
    "driver",
    "print",
    "syntax",
    "typeck",
    "tac",
    "tacgen",
    "tacopt",
    "codegen",
]

cargo-features = ["profile-overrides"]

[profile.dev.overrides."*"]
opt-level = 3